# Файл: docker-compose.yaml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital-market-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=digital_market
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=super_secret_key_change_in_production
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./config:/root/config
    networks:
      - digital-market-network

  postgres:
    image: postgres:14-alpine
    container_name: digital-market-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_market
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - digital-market-network

  redis:
    image: redis:7-alpine
    container_name: digital-market-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - digital-market-network

  migrations:
    image: migrate/migrate
    container_name: digital-market-migrations
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@postgres:5432/digital_market?sslmode=disable", "up"]
    depends_on:
      - postgres
    networks:
      - digital-market-network

volumes:
  postgres-data:
  redis-data:

networks:
  digital-market-network:
    driver: bridge
