# Файл: digital-market/config/config.yml
server:
  port: 8080
  debug: true

# Файл: config/config.yml
db:
  host: localhost
  port: 5432
  user: lapin_ds
  password: postgres
  name: digital_market
  sslmode: disable

jwt:
  secret: super_secret_key_change_in_production
  expires_in: 24h  # 24 часа

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
